name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  testJob:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: test  shell
      run:  echo "TEST_VAR=$(ls -la)">>$GITHUB_ENV
    - name: Test echo
      run: echo ${{ env.TEST_VAR }}
