name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  testJob:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
       RES: 'empty_result'

    steps:
    - name: test  shell
      run:  echo "TEST_VAR=`ls -la`">$RES&&$RES=`ls -la`
    - name: test  echo
      run:  declare -p&&echo $RES
