name: Perf Test fin
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  coreTest:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: step 1  run perf on 1 core
      run: |
        sudo apt-get install stress-ng&&sudo stress-ng --cpu 1 --yaml test.yml --cpu-method matrixprod --metrics-brief -t 60\
        &&mkdir result&&cp test.yml result/cpu_`date +"%d-%m-%Y-%H-%M"`\
        &&grep real-time test.yml | sed 's/[^0-9,/.]*//g'|cut -d . -f 1 >result.file\
        &&echo "-"&&date +"%d-%m-%Y-%H-%M">>result.file\
        &&echo "action_result= `cat result.file`" >> $GITHUB_ENV

    - name: Step 2 - Upload perf result
      uses: actions/upload-artifact@v2
      with: 
          name: perf-res-${{ env.action_result }}
          path: result
