name: Core 1

on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
       TEST: 'testEscho'

    steps:
    - name: 1 core
      run: sudo apt-get install stress-ng&&sudo stress-ng --cpu 1 --yaml test.yml --cpu-method matrixprod --metrics-brief -t 60
    - name: cp report
      run: mkdir wiki&&mv test.yml wiki/cpu_`date +"%d-%m-%Y-%H-%M"`
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
          path: "wiki"
      env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        
    - name: Create graph charts
      uses: alexrogalskiy/github-action-charts@master
      with:
        file: './test.yml'
        name: 'chart'
        path: 'images'
        extension: 'svg'
        width: 400
        height: 400
    - name: ls
      run: ls&&pwd&&echo $TEST&&cat test.yml
