on: 
  workflow_dispatch:
  push:

jobs:
  checking_code:
    runs-on: ubuntu-latest
    
    name: Horusec Scan
    steps:
      - name: Check out conf server
        uses: actions/checkout@master
        with:
             repository: hyper-egor/conf-server
             #path: conf-server
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: -p="./" 
